name: Build Windows & Linux Executable on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_windows:
    name: 🪟 Build Windows App
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build App
        run: |
          flutter pub get
          flutter build windows --release
      - name: Download Visual C++ Redistributable DLLs
        run: |
          Invoke-WebRequest -Uri "https://github.com/My-Quran-Tajwid/visual-cpp-redistributable/archive/refs/heads/main.zip" -OutFile "vcredist.zip"
          Expand-Archive -Path "vcredist.zip" -DestinationPath "temp_vcredist"
          Copy-Item -Path "temp_vcredist\visual-cpp-redistributable-main\*.dll" -Destination "build\windows\x64\runner\Release\" -Force
      - name: Create Windows zip archive
        run: cd build/windows/x64/runner/Release/ && powershell Compress-Archive -Path * -DestinationPath windows-x64.zip
      - name: Upload Windows App to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/windows/x64/runner/Release/windows-x64.zip

  build_linux:
    name: 🐧 Build Linux App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - name: Build App
        run: |
          flutter pub get
          flutter build linux --release
      - name: Create Linux zip archive
        run: cd build/linux/x64/release/bundle/ && zip -r linux-x64.zip *
      - name: Upload Linux App to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/linux/x64/release/bundle/linux-x64.zip
