name: MacOS (Portable)

on:
  workflow_dispatch:

jobs:
  build_linux:
    name:  Build MacOS App
    runs-on: macos-15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build App
        run: |
          flutter pub get
          flutter build macos --release

      - name: Upload App to artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-macos
          path: build/macos/Build/Products/Release/
