name: Windows .EXE (Portable)

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: 🪟 Build Windows App
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Build Windows App
        run: |
          flutter pub get
          flutter build windows --release
          
      - name: Download Visual C++ Redistributable DLLs
        run: |
          Invoke-WebRequest -Uri "https://github.com/My-Quran-Tajwid/visual-cpp-redistributable/archive/refs/heads/main.zip" -OutFile "vcredist.zip"
          Expand-Archive -Path "vcredist.zip" -DestinationPath "temp_vcredist"
          Copy-Item -Path "temp_vcredist\visual-cpp-redistributable-main\*.dll" -Destination "build\windows\x64\runner\Release\" -Force

      - name: Upload Windows App to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-portable
          path: build/windows/x64/runner/Release/

