name: Linux (Portable)

on:
  workflow_dispatch:

jobs:
  build_linux:
    name: 🐧 Build Linux App
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Build Linux App
        run: |
          flutter pub get
          flutter build linux --release

      - name: Upload App to artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: build/linux/x64/release/bundle/
