name: Build Windows Portable .EXE on Demand

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: 🪟 Build Windows App
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Build Windows App
        run: |
          flutter pub get
          flutter build windows --release

      # - run: cd build/windows/x64/runner/Release/ && powershell Compress-Archive -Path * -DestinationPath windows-x64-portable.zip
      - name: Upload Windows App to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-portable
          path: build/windows/x64/runner/Release/

